export const screeningWorkflowsContent = [
    "# Screening Workflows",
    "",
    "This guide provides visual confirmation of the LitLens screening logic, including state transitions, phase progression, and conflict resolution.",
    "",
    "## 1. Core State Machine",
    "",
    "The central logic governing how a study moves from `PENDING` to a final decision.",
    "",
    "\`\`\`mermaid",
    "stateDiagram-v2",
    "    [*] --> PENDING: Import Study",
    "",
    "    PENDING --> SCREENING: First Reviewer Decides",
    "    ",
    "    SCREENING --> SCREENING: Waiting for 2nd Reviewer\\n(Dual Screening Mode)",
    "    SCREENING --> CONFLICT: Disagreement Detected\\n(INCLUDE vs EXCLUDE)",
    "    SCREENING --> INCLUDED: Consensus INCLUDE\\n(Both reviewers agree)",
    "    SCREENING --> EXCLUDED: Consensus EXCLUDE\\n(Both reviewers agree)",
    "    SCREENING --> MAYBE: Consensus MAYBE\\n(Both reviewers agree)",
    "    ",
    "    CONFLICT --> INCLUDED: Lead/Owner Resolves -> INCLUDE",
    "    CONFLICT --> EXCLUDED: Lead/Owner Resolves -> EXCLUDE",
    "    ",
    "    INCLUDED --> PENDING: Phase Advance\\n(TITLE_ABSTRACT -> FULL_TEXT)",
    "    ",
    "    note right of INCLUDED",
    "        ✅ S1 FIX: Auto-advance only ",
    "        on CONSENSUS, not per-decision",
    "    end note",
    "    ",
    "    note right of CONFLICT",
    "        ✅ S3 FIX: Resolution uses",
    "        repository, not direct DB",
    "    end note",
    "\`\`\`",
    "",
    "## 2. Phase Progression",
    "",
    "How studies move through the three screening phases.",
    "",
    "\`\`\`mermaid",
    "flowchart TB",
    "    subgraph TITLE_ABSTRACT[\"Phase 1: Title/Abstract\"]",
    "        TA_PENDING[PENDING] --> TA_SCREENING[SCREENING]",
    "        TA_SCREENING --> TA_CONSENSUS{Consensus?}",
    "        TA_CONSENSUS -->|INCLUDE| TA_INCLUDED[INCLUDED]",
    "        TA_CONSENSUS -->|EXCLUDE| TA_EXCLUDED[EXCLUDED]",
    "        TA_CONSENSUS -->|Disagree| TA_CONFLICT[CONFLICT]",
    "        TA_CONFLICT -->|Resolved| TA_INCLUDED",
    "        TA_CONFLICT -->|Resolved| TA_EXCLUDED",
    "    end",
    "",
    "    subgraph FULL_TEXT[\"Phase 2: Full Text\"]",
    "        FT_PENDING[PENDING] --> FT_SCREENING[SCREENING]",
    "        FT_SCREENING --> FT_CONSENSUS{Consensus?}",
    "        FT_CONSENSUS -->|INCLUDE| FT_INCLUDED[INCLUDED]",
    "        FT_CONSENSUS -->|EXCLUDE| FT_EXCLUDED[EXCLUDED]",
    "        FT_CONSENSUS -->|Disagree| FT_CONFLICT[CONFLICT]",
    "        FT_CONFLICT -->|Resolved| FT_INCLUDED",
    "        FT_CONFLICT -->|Resolved| FT_EXCLUDED",
    "    end",
    "",
    "    subgraph FINAL[\"Phase 3: Final\"]",
    "        F_PENDING[PENDING] --> F_SCREENING[SCREENING]",
    "        F_SCREENING --> F_CONSENSUS{Consensus?}",
    "        F_CONSENSUS -->|INCLUDE| F_INCLUDED[INCLUDED ✓]",
    "        F_CONSENSUS -->|EXCLUDE| F_EXCLUDED[EXCLUDED ✗]",
    "    end",
    "",
    "    TA_INCLUDED -->|\"✅ S1: Auto-Advance\\n(on consensus only)\"| FT_PENDING",
    "    FT_INCLUDED -->|\"Manual Advance\\n(Lead triggers)\"| F_PENDING",
    "",
    "    style TA_INCLUDED fill:#22c55e",
    "    style FT_INCLUDED fill:#22c55e",
    "    style F_INCLUDED fill:#16a34a",
    "    style TA_EXCLUDED fill:#ef4444",
    "    style FT_EXCLUDED fill:#ef4444",
    "    style F_EXCLUDED fill:#dc2626",
    "\`\`\`",
    "",
    "## 3. Conflict Resolution",
    "",
    "The flow for resolving disagreements between reviewers.",
    "",
    "\`\`\`mermaid",
    "flowchart TB",
    "    subgraph Detection[\"Conflict Detection\"]",
    "        D1[Reviewer A: INCLUDE]",
    "        D2[Reviewer B: EXCLUDE]",
    "        D1 & D2 --> SM{StateMachine}",
    "        SM -->|\"uniqueDecisions.size > 1\"| CONFLICT[Create Conflict Record]",
    "    end",
    "",
    "    subgraph Resolution[\"Conflict Resolution\"]",
    "        CONFLICT --> UI[Conflicts Page]",
    "        UI --> Lead[Lead/Owner Reviews]",
    "        Lead --> API[POST /conflicts/{id}/resolve]",
    "        API --> Service[ScreeningService.resolveConflict]",
    "        ",
    "        Service --> Repo1[\"✅ getConflict(id)\"]",
    "        Service --> Repo2[\"✅ createConflictResolution()\"]",
    "        Service --> Repo3[\"✅ updateProjectWorkStatus()\"]",
    "        ",
    "        Note over Repo1,Repo3: Clean Architecture: All via Repository",
    "    end",
    "",
    "    subgraph Result[\"Final State\"]",
    "        Repo3 --> Final{Decision?}",
    "        Final -->|INCLUDE| INC[Status: INCLUDED]",
    "        Final -->|EXCLUDE| EXC[Status: EXCLUDED]",
    "        ",
    "        INC -->|\"Phase == TITLE_ABSTRACT\"| Advance[Auto-Advance to FULL_TEXT]",
    "        INC -->|\"Phase >= FULL_TEXT\"| Ingest[Trigger RAG Ingestion]",
    "    end",
    "",
    "    style CONFLICT fill:#f59e0b",
    "    style INC fill:#22c55e",
    "    style EXC fill:#ef4444",
    "\`\`\`",
    "",
    "## 4. RAG Ingestion Integration",
    "",
    "How and when the AI Knowledge Base is updated.",
    "",
    "\`\`\`mermaid",
    "flowchart LR",
    "    subgraph Triggers[\"Ingestion Triggers\"]",
    "        T1[Consensus INCLUDE\\nat FULL_TEXT]",
    "        T2[Consensus INCLUDE\\nat FINAL]",
    "        T3[Conflict Resolved\\nas INCLUDE]",
    "        T4[Manual Upload]",
    "    end",
    "",
    "    T1 & T2 & T3 --> Queue[BullMQ Queue]",
    "    T4 --> Direct[Direct Pipeline]",
    "",
    "    subgraph Worker[\"Ingestion Worker (Dedicated Process)\"]",
    "        Queue --> W1[IngestionWorker]",
    "        W1 --> W2{PDF Source?}",
    "        ",
    "        W2 -->|\"✅ R2 Cache\"| R2[Download from R2]",
    "        W2 -->|\"No Cache\"| Fetch[Fetch from URL]",
    "        ",
    "        R2 & Fetch --> Validate{Valid PDF?}",
    "        Validate -->|\"✅ R1: MIME Check\"| Parse[pdf-parse]",
    "        Validate -->|\"HTML/Error\"| Fail[Mark FAILED]",
    "        ",
    "        Parse --> Chunk[\"splitTextWithPositions()\\n✅ R5: Track page numbers\"]",
    "        Chunk --> Embed[OpenAI Embeddings]",
    "        Embed --> Store[(DocumentChunk)]",
    "    end",
    "",
    "    Direct --> Validate",
    "",
    "    subgraph Status[\"ProjectWork Update\"]",
    "        Store --> Success[ingestionStatus: COMPLETED]",
    "        Fail --> Failed[ingestionStatus: FAILED\\ningestionError: message]",
    "    end",
    "",
    "    style Success fill:#22c55e",
    "    style Failed fill:#ef4444",
    "\`\`\`",
    ""
].join("\n");
